/** Shared styles are authored only against semantic tokens. Shadow roots isolate host resets. */
export const chatStyles = `
:host{all:initial;color-scheme:light;display:block;font-family:var(--ae-chat-font-family);font-size:var(--ae-chat-font-size);color:var(--ae-chat-text);line-height:1.6;text-align:start}
*,*::before,*::after{box-sizing:border-box} [hidden]{display:none!important} button,input,textarea,select{font:inherit}button,a,select,textarea{touch-action:manipulation}button{cursor:pointer}button:disabled{cursor:default;background:var(--ae-chat-disabled-background);color:var(--ae-chat-disabled-text);border-color:var(--ae-chat-border)}
:focus-visible{outline:3px solid var(--ae-chat-focus);outline-offset:3px}::selection{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}a{color:var(--ae-chat-accent-text);text-underline-offset:3px}p,h2,h3{margin:0}.ae-icon{width:20px;height:20px;flex:none}.ae-visually-hidden{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.ae-button{min-height:var(--ae-chat-control-height);padding:8px 12px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-control-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);font-weight:500;white-space:nowrap}.ae-button:hover:not(:disabled){background:var(--ae-chat-surface);border-color:var(--ae-chat-accent-text)}.ae-button-primary{background:var(--ae-chat-accent);color:var(--ae-chat-on-accent);border-color:var(--ae-chat-accent-text)}.ae-button-primary:hover:not(:disabled){background:var(--ae-chat-accent);filter:brightness(.93)}.ae-button-quiet{border-color:transparent;background:transparent}.ae-icon-button{width:var(--ae-chat-control-height);padding:8px}.ae-status{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}
.ae-page{height:100%;min-height:0;display:flex;flex-direction:row;background:var(--ae-chat-canvas);color:var(--ae-chat-text);position:relative;overflow:hidden}.ae-header{display:flex;align-items:center;gap:12px;padding:8px var(--ae-chat-space);flex:none}.ae-heading{min-width:0;flex:1}.ae-title{font-size:18px;font-weight:650;overflow-wrap:anywhere}.ae-toolbar{display:flex;align-items:center;gap:4px;flex:none}.ae-select-label{min-width:0;flex:1;color:var(--ae-chat-muted);font-size:var(--ae-chat-small-font-size)}.ae-select{display:block;width:100%;min-height:var(--ae-chat-control-height);border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-control-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);padding:8px;margin-top:4px;overflow:hidden;text-overflow:ellipsis;font-size:var(--ae-chat-font-size)}
.ae-history{max-height:35%;overflow:auto;flex:none;background:var(--ae-chat-surface);padding:12px var(--ae-chat-space);border-bottom:1px solid var(--ae-chat-border)}.ae-history h3{font-size:var(--ae-chat-font-size);margin-bottom:8px}.ae-history-item{display:block;text-align:start;white-space:normal;width:100%;border:0;background:transparent;padding:12px;color:var(--ae-chat-text);border-radius:var(--ae-chat-control-radius);font:inherit}.ae-history-item:hover,.ae-history-item[aria-current=true]{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}.ae-history-item small{display:block;color:var(--ae-chat-muted);font-size:var(--ae-chat-small-font-size)}
.ae-transcript{flex:1;min-height:0;overflow:auto;padding:24px var(--ae-chat-space);overscroll-behavior:contain;scrollbar-color:var(--ae-chat-border) var(--ae-chat-surface);scrollbar-width:thin;overflow-anchor:none}.ae-welcome{padding:0;max-width:720px;margin:24px auto}.ae-welcome h3{font-size:22px;font-weight:650;line-height:1.35;margin-bottom:12px}.ae-welcome p{color:var(--ae-chat-muted);margin-bottom:20px}.ae-suggestions{display:flex;flex-direction:column;align-items:flex-start;gap:4px}.ae-suggestions .ae-button{max-width:100%;white-space:normal;overflow-wrap:anywhere;text-align:start;justify-content:flex-start;border-color:transparent;background:var(--ae-chat-surface);font-size:14px}.ae-turn{max-width:720px;margin:0 auto 28px}.ae-message{margin-bottom:16px}.ae-message-self{display:flex;flex-direction:column;align-items:flex-end}.ae-message-name{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);margin-bottom:6px}.ae-message-text{white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;font-size:var(--ae-chat-font-size);line-height:1.8}.ae-message-self .ae-message-text{padding:12px 16px;border-radius:var(--ae-chat-message-radius);background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}.ae-message-agent{padding:0 2px}.ae-turn-state{margin-top:8px;font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}.ae-error-text{color:var(--ae-chat-danger)}
.ae-run-details{margin-top:4px;font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}.ae-run-details summary{cursor:pointer;padding:10px 0;min-height:var(--ae-chat-control-height);display:list-item}.ae-run-details p{margin:4px 0}.ae-operation{padding:8px 0;overflow-wrap:anywhere}.ae-operation strong{font-weight:600;color:var(--ae-chat-text)}.ae-jump{align-self:center;flex:none;margin:4px 0;font-size:var(--ae-chat-small-font-size)}
.ae-feedback{flex:none;padding:12px var(--ae-chat-space);border-top:1px solid var(--ae-chat-border);color:var(--ae-chat-danger);font-size:13px;overflow-wrap:anywhere}.ae-feedback-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.ae-composer{flex:none;width:100%;max-width:760px;align-self:center;padding:8px var(--ae-chat-space) max(12px,env(safe-area-inset-bottom));background:var(--ae-chat-canvas)}.ae-composer-surface{border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-panel-radius);background:var(--ae-chat-surface);overflow:visible}.ae-composer-surface:focus-within{border-color:var(--ae-chat-focus)}.ae-input-label{display:block}.ae-input{display:block;width:100%;min-height:60px;max-height:144px;resize:vertical;border:0;border-radius:var(--ae-chat-panel-radius);padding:12px 14px 4px;background:transparent;color:var(--ae-chat-text);caret-color:var(--ae-chat-accent-text);font-size:16px;line-height:1.5}.ae-input::placeholder{color:var(--ae-chat-muted)}.ae-composer-surface:has(.ae-input:focus-visible){outline:3px solid var(--ae-chat-focus);outline-offset:3px}.ae-input:focus-visible{outline:none}.ae-composer-footer{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:4px 8px 8px 14px}.ae-input-count{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);font-variant-numeric:tabular-nums}.ae-composer-actions{display:flex;gap:8px;margin-left:auto}.ae-composer-actions .ae-button{font-size:14px}.ae-footnote{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);margin-top:6px;line-height:1.5}.ae-page[data-narrow=true] .ae-keyboard-hint{display:none}.ae-page[data-narrow=true] .ae-transcript{padding-block:16px}.ae-sources{display:flex;flex-wrap:wrap;gap:4px 16px;font-size:var(--ae-chat-small-font-size);margin:8px 0;overflow-wrap:anywhere}.ae-sources a{padding-block:6px;max-width:100%}
.ae-launcher{position:fixed;right:24px;bottom:max(24px,env(safe-area-inset-bottom));width:56px;height:56px;border-radius:50%;border:1px solid var(--ae-chat-accent-text);background:var(--ae-chat-accent);color:var(--ae-chat-on-accent);display:flex;align-items:center;justify-content:center;pointer-events:auto}.ae-launcher .ae-icon{width:26px;height:26px}.ae-launcher:hover{filter:brightness(.93)}
.ae-dialog{position:fixed;inset:auto 24px 92px auto;margin:0;padding:0;width:min(var(--ae-chat-panel-width),calc(100vw - 32px));height:min(var(--ae-chat-panel-height),calc(var(--ae-chat-viewport-height,100dvh) - 116px));max-width:none;max-height:none;border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-panel-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);overflow:hidden;pointer-events:auto;font:inherit}.ae-dialog[open]{display:flex;flex-direction:column;animation:ae-open var(--ae-chat-motion-ms) cubic-bezier(.16,1,.3,1)}.ae-dialog[data-mobile=true]{inset:var(--ae-chat-viewport-top,0px) 0 auto 0;width:100vw;height:var(--ae-chat-viewport-height,100dvh);border:0;border-radius:0}.ae-dialog::backdrop{background:var(--ae-chat-canvas)}.ae-dialog .ae-page{width:100%}

.ae-chat-main,.ae-main-body,.ae-conversation{display:flex;flex-direction:column;min-width:0;min-height:0;flex:1}.ae-main-body{position:relative}.ae-header{gap:8px;min-height:64px}.ae-toolbar{align-items:center;gap:4px;flex-wrap:wrap}.ae-toolbar .ae-button{font-size:14px}.ae-toolbar .ae-status{margin-left:auto}.ae-toolbar .ae-button[aria-expanded=true]{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}
.ae-sidebar{width:232px;flex:none;min-height:0;display:flex;flex-direction:column;background:var(--ae-chat-surface);border-right:1px solid var(--ae-chat-border)}.ae-sidebar-header,.ae-detail-header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:12px var(--ae-chat-space);min-height:64px;flex:none}.ae-sidebar-header h2,.ae-detail-header h3{font-size:16px;font-weight:650}.ae-new-session{margin:0 12px 16px;justify-content:flex-start}.ae-sidebar .ae-history{flex:1;max-height:none;min-height:0;border:0;padding:0 8px 12px;scrollbar-color:var(--ae-chat-border) var(--ae-chat-surface);scrollbar-width:thin}.ae-sidebar .ae-history-title{display:none}.ae-sidebar .ae-select-label{flex:none;padding:0 var(--ae-chat-space) 12px}.ae-sidebar .ae-history-item{margin-bottom:4px}.ae-history-title-text{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere;font-weight:500;font-size:14px}.ae-history-item small{margin-top:6px}.ae-history-item:disabled{opacity:1;color:var(--ae-chat-muted)}.ae-sidebar .ae-history-item[aria-current=true]{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}.ae-sidebar .ae-status{padding:12px 8px}
.ae-sidebar-backdrop,.ae-detail-backdrop{position:absolute;inset:0;border:0;padding:0;background:var(--ae-chat-canvas);opacity:.55;z-index:2;cursor:default}.ae-page[data-wide=false] .ae-sidebar{position:absolute;inset:0 auto 0 0;width:min(280px,calc(100% - 32px));z-index:3}.ae-detail-panel{position:absolute;inset:0 0 0 auto;width:min(360px,100%);z-index:3;display:flex;flex-direction:column;min-height:0;border-left:1px solid var(--ae-chat-border);background:var(--ae-chat-canvas)}.ae-detail-header{border-bottom:1px solid var(--ae-chat-border)}.ae-session-details{overflow:auto;min-height:0;padding:16px;scrollbar-color:var(--ae-chat-border) var(--ae-chat-surface);scrollbar-width:thin}.ae-detail-note{font-size:13px;line-height:1.75;color:var(--ae-chat-muted);margin:0 0 16px}.ae-session-fields{margin:0}.ae-session-fields dt{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);margin:16px 0 4px}.ae-session-fields dt:first-child{margin-top:0}.ae-session-fields dd{margin:0;overflow-wrap:anywhere;line-height:1.7}.ae-session-id,.ae-tool-name{font:12px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.ae-tool-list{list-style:none;margin:0;padding:0}.ae-tool-item{padding:16px 0;border-top:1px solid var(--ae-chat-border)}.ae-tool-item:first-child{padding-top:0;border-top:0}.ae-tool-heading{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.ae-tool-heading h4{font-size:15px;font-weight:650;margin:0;overflow-wrap:anywhere}.ae-tool-kind{font-size:12px;color:var(--ae-chat-muted);white-space:nowrap}.ae-tool-name{display:block;margin-top:4px;color:var(--ae-chat-muted)}.ae-tool-item p{margin-top:8px;font-size:13px;line-height:1.75;color:var(--ae-chat-muted)}.ae-detail-subtitle{font-size:16px;margin:24px 0 12px}.ae-page[data-narrow=true] .ae-header{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:0 4px;padding:6px 12px}.ae-page[data-narrow=true] .ae-toolbar{grid-row:2;grid-column:1/-1;gap:2px;justify-content:flex-end}.ae-page[data-narrow=true] .ae-header>.ae-icon-button:last-child{grid-row:1;grid-column:3}.ae-page[data-narrow=true] .ae-toolbar .ae-button:not(.ae-icon-button) .ae-icon{display:none}.ae-page[data-narrow=true] .ae-toolbar .ae-button{padding-inline:10px}.ae-page[data-narrow=true] .ae-heading{display:flex;align-items:baseline;flex-wrap:wrap;gap:0 8px}.ae-page[data-narrow=true] .ae-title{font-size:16px}.ae-page[data-narrow=true] .ae-welcome{margin:8px auto}.ae-page[data-narrow=true] .ae-welcome h3{font-size:20px}.ae-page[data-narrow=true] .ae-detail-panel{width:100%;border-left:0}
@keyframes ae-open{from{transform:translateY(8px);opacity:.7}to{transform:translateY(0);opacity:1}}@media(prefers-reduced-motion:reduce){.ae-dialog[open]{animation:none}}@media(forced-colors:active){.ae-button,.ae-launcher,.ae-dialog{border:1px solid ButtonText}}
`;
export function installChatStyles(root: ShadowRoot, nonce?: string) {
  if (
    "adoptedStyleSheets" in root &&
    "replaceSync" in CSSStyleSheet.prototype
  ) {
    const sheet = new CSSStyleSheet();
    sheet.replaceSync(chatStyles);
    root.adoptedStyleSheets = [...root.adoptedStyleSheets, sheet];
  } else {
    const style = document.createElement("style");
    if (nonce) style.nonce = nonce;
    style.textContent = chatStyles;
    root.append(style);
  }
}
