/** Shared styles are authored only against semantic tokens. Shadow roots isolate host resets. */
export const chatStyles = `
:host{all:initial;color-scheme:light;display:block;font-family:var(--ae-chat-font-family);font-size:var(--ae-chat-font-size);color:var(--ae-chat-text);line-height:1.6;text-align:start}
*,*::before,*::after{box-sizing:border-box} [hidden]{display:none!important} button,input,textarea,select{font:inherit}button,a,select,textarea{touch-action:manipulation}button{cursor:pointer}button:disabled{cursor:default;background:var(--ae-chat-disabled-background);color:var(--ae-chat-disabled-text);border-color:var(--ae-chat-border)}
:focus-visible{outline:3px solid var(--ae-chat-focus);outline-offset:3px}::selection{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}a{color:var(--ae-chat-accent-text);text-underline-offset:3px}p,h2,h3{margin:0}.ae-icon{width:20px;height:20px;flex:none}.ae-visually-hidden{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.ae-button{min-height:var(--ae-chat-control-height);padding:8px 12px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-control-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);font-weight:600;white-space:nowrap}.ae-button:hover:not(:disabled){background:var(--ae-chat-surface);border-color:var(--ae-chat-accent-text)}.ae-button-primary{background:var(--ae-chat-accent);color:var(--ae-chat-on-accent);border-color:var(--ae-chat-accent-text)}.ae-button-primary:hover:not(:disabled){background:var(--ae-chat-accent);filter:brightness(.93)}.ae-button-quiet{border-color:transparent;background:transparent}.ae-icon-button{width:var(--ae-chat-control-height);padding:8px}.ae-status{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}
.ae-page{height:100%;min-height:0;display:flex;flex-direction:column;background:var(--ae-chat-canvas);color:var(--ae-chat-text);position:relative;overflow:hidden}.ae-header{display:flex;align-items:center;gap:12px;padding:var(--ae-chat-space);border-bottom:1px solid var(--ae-chat-border);flex:none}.ae-heading{min-width:0;flex:1}.ae-title{font-size:18px;font-weight:650;overflow-wrap:anywhere}.ae-toolbar{display:flex;align-items:end;gap:8px;padding:12px var(--ae-chat-space);border-bottom:1px solid var(--ae-chat-border);flex:none}.ae-select-label{min-width:0;flex:1;color:var(--ae-chat-muted);font-size:var(--ae-chat-small-font-size)}.ae-select{display:block;width:100%;min-height:var(--ae-chat-control-height);border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-control-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);padding:8px;margin-top:4px;overflow:hidden;text-overflow:ellipsis;font-size:var(--ae-chat-font-size)}
.ae-history{max-height:35%;overflow:auto;flex:none;background:var(--ae-chat-surface);padding:12px var(--ae-chat-space);border-bottom:1px solid var(--ae-chat-border)}.ae-history h3{font-size:var(--ae-chat-font-size);margin-bottom:8px}.ae-history-item{display:block;text-align:start;white-space:normal;width:100%;border:0;background:transparent;padding:12px;color:var(--ae-chat-text);border-radius:var(--ae-chat-control-radius);font:inherit}.ae-history-item:hover,.ae-history-item[aria-current=true]{background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}.ae-history-item small{display:block;color:var(--ae-chat-muted);font-size:var(--ae-chat-small-font-size)}
.ae-transcript{flex:1;min-height:0;overflow:auto;padding:24px var(--ae-chat-space);overscroll-behavior:contain;scrollbar-color:var(--ae-chat-border) var(--ae-chat-surface);scrollbar-width:thin;overflow-anchor:none}.ae-welcome{padding:24px 0;max-width:60ch;margin:auto}.ae-welcome h3{font-size:22px;font-weight:650;line-height:1.35;margin-bottom:12px}.ae-welcome p{color:var(--ae-chat-muted);margin-bottom:20px}.ae-suggestions{display:flex;flex-wrap:wrap;gap:8px}.ae-turn{max-width:70ch;margin:0 auto 28px}.ae-message{margin-bottom:16px}.ae-message-self{display:flex;flex-direction:column;align-items:flex-end}.ae-message-name{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);margin-bottom:6px}.ae-message-text{white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;font-size:var(--ae-chat-font-size);line-height:1.7}.ae-message-self .ae-message-text{padding:12px 16px;border-radius:var(--ae-chat-message-radius);background:var(--ae-chat-user-background);color:var(--ae-chat-user-text)}.ae-message-agent{padding:0 2px}.ae-turn-state{margin-top:8px;font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}.ae-error-text{color:var(--ae-chat-danger)}
.ae-run-details{margin-top:12px;border-top:1px solid var(--ae-chat-border);font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted)}.ae-run-details summary{cursor:pointer;padding:10px 0;min-height:var(--ae-chat-control-height);display:list-item}.ae-run-details p{margin:4px 0}.ae-operation{padding:8px 0;overflow-wrap:anywhere}.ae-operation strong{font-weight:600;color:var(--ae-chat-text)}.ae-jump{align-self:center;flex:none;margin:4px 0;font-size:var(--ae-chat-small-font-size)}
.ae-feedback{flex:none;padding:12px var(--ae-chat-space);border-top:1px solid var(--ae-chat-border);color:var(--ae-chat-danger);font-size:13px;overflow-wrap:anywhere}.ae-feedback-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.ae-composer{flex:none;padding:12px var(--ae-chat-space) max(12px,env(safe-area-inset-bottom));border-top:1px solid var(--ae-chat-border);background:var(--ae-chat-canvas)}.ae-input-label{display:block}.ae-input{display:block;width:100%;min-height:68px;max-height:144px;resize:vertical;border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-control-radius);padding:12px;background:var(--ae-chat-canvas);color:var(--ae-chat-text);caret-color:var(--ae-chat-accent-text);font-size:16px;line-height:1.5}.ae-input::placeholder{color:var(--ae-chat-muted)}.ae-composer-footer{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:8px}.ae-input-count{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);font-variant-numeric:tabular-nums}.ae-composer-actions{display:flex;gap:8px}.ae-footnote{font-size:var(--ae-chat-small-font-size);color:var(--ae-chat-muted);margin-top:8px}.ae-page[data-narrow=true] .ae-keyboard-hint{display:none}.ae-page[data-narrow=true] .ae-header{padding-block:12px}.ae-page[data-narrow=true] .ae-transcript{padding-block:16px}
.ae-launcher{position:fixed;right:24px;bottom:max(24px,env(safe-area-inset-bottom));width:56px;height:56px;border-radius:50%;border:1px solid var(--ae-chat-accent-text);background:var(--ae-chat-accent);color:var(--ae-chat-on-accent);display:flex;align-items:center;justify-content:center;pointer-events:auto}.ae-launcher .ae-icon{width:26px;height:26px}.ae-launcher:hover{filter:brightness(.93)}
.ae-dialog{position:fixed;inset:auto 24px 92px auto;margin:0;padding:0;width:min(var(--ae-chat-panel-width),calc(100vw - 32px));height:min(var(--ae-chat-panel-height),calc(var(--ae-chat-viewport-height,100dvh) - 116px));max-width:none;max-height:none;border:1px solid var(--ae-chat-border);border-radius:var(--ae-chat-panel-radius);background:var(--ae-chat-canvas);color:var(--ae-chat-text);overflow:hidden;pointer-events:auto;font:inherit}.ae-dialog[open]{display:flex;flex-direction:column;animation:ae-open var(--ae-chat-motion-ms) cubic-bezier(.16,1,.3,1)}.ae-dialog[data-mobile=true]{inset:var(--ae-chat-viewport-top,0px) 0 auto 0;width:100vw;height:var(--ae-chat-viewport-height,100dvh);border:0;border-radius:0}.ae-dialog::backdrop{background:var(--ae-chat-canvas)}.ae-dialog .ae-page{width:100%}
@keyframes ae-open{from{transform:translateY(8px);opacity:.7}to{transform:translateY(0);opacity:1}}@media(prefers-reduced-motion:reduce){.ae-dialog[open]{animation:none}}@media(forced-colors:active){.ae-button,.ae-launcher,.ae-dialog{border:1px solid ButtonText}}
`;
export function installChatStyles(root: ShadowRoot, nonce?: string) {
  if (
    "adoptedStyleSheets" in root &&
    "replaceSync" in CSSStyleSheet.prototype
  ) {
    const sheet = new CSSStyleSheet();
    sheet.replaceSync(chatStyles);
    root.adoptedStyleSheets = [...root.adoptedStyleSheets, sheet];
  } else {
    const style = document.createElement("style");
    if (nonce) style.nonce = nonce;
    style.textContent = chatStyles;
    root.append(style);
  }
}
